# Subaligner Ubuntu 20 Docker Image
FROM ubuntu:20.10

ARG RELEASE_VERSION

ENV RELEASE_VERSION=v0.2.1
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London

RUN ["/bin/bash", "-c", "apt-get -y update &&\
    apt-get -y install ffmpeg &&\
    apt-get -y install espeak libespeak1 libespeak-dev espeak-data &&\
    apt-get -y install libsndfile-dev &&\
    apt-get -y install python3-dev &&\
    apt-get -y install python3-tk &&\
    apt-get -y install python3-pip &&\
    python3 -m pip install --upgrade pip &&\
    python3 -m pip install 'subaligner[harmony]==0.2.1'"]
