# Subaligner Debian docker image
FROM debian:stable-20201209

ARG SOURCE_BRANCH
ENV SOURCE_BRANCH $SOURCE_BRANCH

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
RUN apt-get -y update &&\
    apt-get -y install ffmpeg &&\
    apt-get -y install espeak libespeak1 libespeak-dev espeak-data &&\
    apt-get -y install libsndfile-dev &&\
    apt-get -y install python3-dev &&\
    apt-get -y install python3-tk &&\
    apt-get -y install python3-pip &&\
    python3 -m pip install --upgrade pip &&\
    python3 -m pip install numpy &&\
    python3 -m pip install subaligner==${SOURCE_BRANCH:1}
