# Subaligner CentOS 8 Docker Image
From centos:8

RUN dnf install -y epel-release dnf-utils &&\
    yum-config-manager --set-enabled PowerTools &&\
    yum-config-manager --add-repo=https://negativo17.org/repos/epel-multimedia.repo &&\
    dnf install -y ffmpeg &&\
    dnf install -y espeak-ng &&\
    ln -s /usr/lib64/libespeak-ng.so.1 /usr/lib64/libespeak.so &&\
    dnf install -y libsndfile-devel &&\
    dnf install -y python3 &&\
    dnf install -y gcc &&\
    dnf install -y python3-wheel &&\
    dnf install -y python3-devel &&\
    dnf install -y python3-pip &&\
    pip3 install --upgrade pip &&\
    python3 -m pip install numpy &&\
    python3 -m pip install subaligner