# Subaligner Fedora Docker Image
From fedora:34

ARG RELEASE_VERSION

ENV RELEASE_VERSION=${RELEASE_VERSION}
ENV DOCKER_BUILDKIT=0
ENV COMPOSE_DOCKER_CLI_BUILD=0


RUN ["/bin/bash", "-c", "dnf install -y dnf-utils &&\
    yum install -y dnf-plugins-core &&\
    dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm &&\
    dnf install -y ffmpeg &&\
    dnf install -y espeak-ng &&\
    ln -s /usr/lib64/libespeak-ng.so.1 /usr/lib64/libespeak.so &&\
    dnf install -y libsndfile-devel &&\
    dnf install -y blas lapack blas-devel lapack-devel &&\
    dnf install -y gcc-c++ &&\
    dnf install -y python3 &&\
    dnf install -y gcc &&\
    dnf install -y python3-wheel &&\
    dnf install -y python3-devel &&\
    dnf install -y python3-pip &&\
    dnf install -y hdf5 hdf5-devel &&\
    pip3 install --upgrade pip &&\
    python3 -m pip install --upgrade \"setuptools<65.0.0\" wheel &&\
    python3 -m pip install \"subaligner==${RELEASE_VERSION}\" &&\
    python3 -m pip install \"subaligner[harmony]==${RELEASE_VERSION}\""]
