# Subaligner Ubuntu 22 Docker Image
FROM ubuntu:22.04

ARG RELEASE_VERSION

ENV RELEASE_VERSION=${RELEASE_VERSION}
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London

RUN ["/bin/bash", "-c", "apt-get -y update &&\
    apt-get -y install ffmpeg &&\
    apt-get -y install espeak libespeak1 libespeak-dev espeak-data &&\
    apt-get -y install libsndfile-dev &&\
    apt-get -y install libhdf5-dev &&\
    apt-get -y install python3-dev &&\
    apt-get -y install python3-tk &&\
    apt-get -y install python3-pip &&\
    python3 -m pip install --upgrade pip &&\
    python3 -m pip install --upgrade \"setuptools<65.0.0\" wheel &&\
    python3 -m pip install \"subaligner==${RELEASE_VERSION}\" &&\
    python3 -m pip install \"subaligner[harmony]==${RELEASE_VERSION}\""]
