# Subaligner Ubuntu 20 Docker Image
FROM ubuntu:20.10

ARG RELEASE_VERSION

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London
RUN ["/bin/bash", "-c", "apt-get -y update &&\
    apt-get -y install ffmpeg &&\
    apt-get -y install espeak libespeak1 libespeak-dev espeak-data &&\
    apt-get -y install libsndfile-dev &&\
    apt-get -y install python3-dev &&\
    apt-get -y install python3-tk &&\
    apt-get -y install python3-pip &&\
    python3 -m pip install --upgrade pip &&\
    python3 -m pip install 'numpy<1.20.0' &&\
    python3 -m pip install subaligner==${RELEASE_VERSION:1}"]
