# Subaligner Debian docker image
FROM debian:stable-20211011-slim

ARG RELEASE_VERSION

ENV DEBIAN_FRONTEND=noninteractive
ENV RELEASE_VERSION=${RELEASE_VERSION}
ENV TZ=Europe/London

RUN ["/bin/bash", "-c", "apt -y update &&\
    apt -y install ffmpeg &&\
    apt -y install espeak libespeak1 libespeak-dev espeak-data &&\
    apt -y install libsndfile-dev &&\
    apt -y install python3-dev &&\
    apt -y install python3-tk &&\
    apt -y install python3-pip &&\
    python3 -m pip install --upgrade pip &&\
    python3 -m pip install \"subaligner==${RELEASE_VERSION}\" &&\
    python3 -m pip install \"subaligner[harmony]==${RELEASE_VERSION}\""]
