{0}{0}25.0
{311}{374}I've spent nearly two decades
{374}{463}observing what makes people luckier than others
{464}{553}and trying to help people increase their luck.
{567}{639}You see, I teach entrepreneurship,
{640}{728}and we all know that most new ventures fail,
{729}{820}and innovators and entrepreneurs need all the luck they can get.
{846}{878}So what is luck?
{879}{1030}Luck is defined as success or failure apparently caused by chance.
{1057}{1092}Apparently.
{1092}{1133}That's the operative word.
{1159}{1209}It looks like it's chance
{1210}{1339}because we rarely see all the levers that come into play to make people lucky.
{1339}{1414}But I've realized, by watching so long,
{1415}{1498}that luck is rarely a lightning strike,
{1499}{1542}isolated and dramatic.
{1542}{1542}(SOUND EFFECT)
{1542}{1542}(SOUND EFFECT)