{0}{0}25.0
{311}{374}I've spent nearly two decades
{374}{463}observing what makes people luckier than others
{464}{553}and trying to help people increase their luck.
{567}{639}You see, I teach entrepreneurship,
{640}{728}and we all know that most new ventures fail,
{729}{820}and innovators and entrepreneurs need all the luck they can get.
{846}{878}So what is luck?
{879}{1030}Luck is defined as success or failure apparently caused by chance.
{1057}{1092}Apparently.
{1092}{1133}That's the operative word.
{1159}{1209}It looks like it's chance
{1210}{1339}because we rarely see all the levers that come into play to make people lucky.
{1339}{1414}But I've realized, by watching so long,
{1415}{1498}that luck is rarely a lightning strike,
{1499}{1542}isolated and dramatic.
{1556}{1616}It's much more like the wind,
{1616}{1656}blowing constantly.
{1656}{1695}Sometimes it's calm,
{1696}{1749}and sometimes it blows in gusts,
{1749}{1855}and sometimes it comes from directions that you didn't even imagine.
{1855}{1917}So how do you catch the winds of luck?
{1940}{2005}It's easy, but it's not obvious.
{2017}{2090}So I'm going to share three things with you
{2091}{2221}that you can do to build a sail to capture the winds of luck.
{2241}{2285}The first thing you want to do
{2286}{2348}is to change your relationship with yourself.
{2349}{2452}Be willing to take small risks that get you out of your comfort zone.
{2452}{2537}Now, when we're children, we do this all the time.
{2561}{2642}We have to do this if we're going to learn how to walk or talk
{2643}{2672}or ride a bike
{2673}{2721}or even quantum mechanics. Right?
{2722}{2795}We need to go from someone one week who doesn't ride a bike
{2796}{2840}to, next week, someone who does.
{2841}{2905}And this requires us to get out of our comfort zone
{2905}{2950}and take some risks.
{2951}{3004}The problem is, as we get older,
{3004}{3051}we rarely do this.
{3052}{3108}We sort of lock down the sense of who we are
{3109}{3154}and don't stretch anymore.
{3154}{3194}Now, with my students,
{3195}{3266}I spend a lot of time giving them encouragement
{3267}{3330}to get out of their comfort zone and take some risks.
{3345}{3374}How do I do this?
{3374}{3471}Well, I start out by having them fill out a risk-o-meter.
{3472}{3541}Now, it's basically a fun thing we developed in our class
{3542}{3618}where they map out what risks they're willing to take.
{3618}{3691}And it becomes clear very quickly to them
{3691}{3743}that risk-taking is not binary.
{3756}{3847}There are intellectual risks and physical risks and financial risks
{3848}{3948}and emotional risks and social risks and ethical risks and political risks.
{3948}{4043}And once they do this, they compare their risk profiles with others,
{4043}{4126}and they quickly realize that they're all really different.
{4150}{4214}I then encourage them to stretch,
{4215}{4287}to take some risks that get them out of their comfort zone.
{4287}{4371}For example, I might ask them to do an intellectual risk
{4372}{4449}and try to tackle a problem they haven't tried before;
{4449}{4562}or a social risk, talking to someone sitting next to them on the train;
{4562}{4606}or an emotional risk,
{4606}{4680}maybe telling someone they really care about how they feel.
{4708}{4769}I do this myself all the time.
{4782}{4842}About a dozen years ago, I was on an airplane,
{4843}{4912}early, early morning flight on my way to Ecuador.
{4912}{5056}And normally, I would just put on my headphones
{5056}{5104}and go to sleep, wake up, do some work,
{5105}{5149}but I decided to take a little risk,
{5150}{5221}and I started a conversation with the man sitting next to me.
{5222}{5302}I introduced myself, and I learned that he was a publisher.
{5342}{5371}Interesting.
{5372}{5428}We ended up having a fascinating conversation.
{5429}{5499}I learned all about the future of the publishing industry.
{5499}{5579}So about three quarters of the way through the flight,
{5580}{5624}I decided to take another risk,
{5625}{5724}and I opened up my laptop and I shared with him a book proposal
{5724}{5824}I put together for something I was doing in my class.
{5824}{5867}And he was very polite, he read it,
{5868}{5937}and he said, "You know what, Tina, this isn't right for us,
{5938}{5979}but thank you so much for sharing."
{5980}{6031}It's OK. That risk didn't work out.
{6044}{6076}I shut my laptop.
{6076}{6151}At the end of the flight, we exchanged contact information.
{6190}{6250}A couple of months later, I reached out to him,
{6251}{6317}and I said, "Mark, would you like to come to my class?
{6317}{6386}I'm doing a project on reinventing the book,
{6387}{6420}the future of publishing."
{6420}{6467}And he said, "Great. I'd love to come."
{6467}{6526}So he came to my class. We had a great experience.
{6526}{6579}A few months later, I wrote to him again.
{6579}{6646}This time, I sent him a bunch of video clips
{6647}{6702}from another project my students had done.
{6724}{6788}He was so intrigued
{6788}{6843}by one of the projects the students had done,
{6844}{6893}he thought there might be a book in it,
{6894}{6947}and he wanted to meet those students.
{6956}{7010}I have to tell you, I was a little bit hurt.
{7036}{7112}I mean, he wanted to do a book with my students and not with me,
{7113}{7141}but OK, it's all right.
{7142}{7230}So I invited him to come down, and he and his colleagues came to Stanford
{7230}{7316}and met with the students, and afterwards, we had lunch together.
{7337}{7382}And one of his editors said to me,
{7383}{7453}"Hey, have you ever considered writing a book?"
{7473}{7518}I said, "Funny you should ask."
{7519}{7596}And I pulled out the exact same proposal
{7597}{7681}that I had showed his boss a year earlier.
{7682}{7742}Within two weeks, I had a contract,
{7743}{7840}and within two years, the book had sold over a million copies around the world.
{7906}{7956}Now, you might say,
{7957}{7991}"Oh, you're so lucky."
{7991}{8023}But of course I was lucky,
{8024}{8132}but that luck resulted from a series of small risks I took,
{8132}{8189}starting with saying hello.
{8190}{8250}And anyone can do this,
{8250}{8294}no matter where you are in your life,
{8295}{8341}no matter where you are in the world --
{8342}{8424}even if you think you're the most unlucky person,
{8425}{8532}you can do this by taking little risks that get you out of your comfort zone.
{8532}{8591}You start building a sail to capture luck.
{8615}{8659}The second thing you want to do
{8659}{8727}is to change your relationship with other people.
{8728}{8862}You need to understand that everyone who helps you on your journey
{8862}{8959}is playing a huge role in getting you to your goals.
{8960}{9025}And if you don't show appreciation,
{9026}{9083}not only are you not closing the loop,
{9084}{9127}but you're missing an opportunity.
{9160}{9211}When someone does something for you,
{9211}{9243}they're taking that time
{9243}{9323}that they could be spending on themselves or someone else,
{9324}{9386}and you need to acknowledge what they're doing.
{9412}{9519}Now, I run three fellowship programs at Stanford,
{9520}{9572}and they are very competitive to get into,
{9573}{9654}and when I send out the letters to those students who don't get in,
{9654}{9729}I always know there are going to be people who are disappointed.
{9730}{9809}Some of the people who are disappointed send me notes, complaining.
{9810}{9850}Some of them send notes
{9851}{9937}saying what could I do to make myself more successful next time around?
{9937}{9970}And every once in a while,
{9971}{10054}someone sends me a note thanking me for the opportunity.
{10072}{10115}This happened about seven years ago.
{10116}{10184}A young man named Brian sent me a beautiful note saying,
{10184}{10266}"I know I've been rejected from this program twice,
{10266}{10319}but I want to thank you for the opportunity.
{10319}{10386}I learned so much through the process of applying."
{10405}{10502}I was so taken by the graciousness of his message
{10503}{10555}that I invited him to come and meet me.
{10555}{10625}And we spent some time chatting and cooked up an idea
{10626}{10676}for an independent study project together.
{10702}{10751}He was on the football team at Stanford,
{10752}{10850}and he decided to do a project on looking at leadership in that context.
{10859}{10950}We got to know each other incredibly well through that quarter,
{10950}{11010}and he took the project that he started working on
{11011}{11044}in the independent study
{11044}{11156}and turned it, ultimately, into a company called Play for Tomorrow,
{11157}{11231}where he teaches kids from disadvantaged backgrounds
{11232}{11302}how to, essentially, craft the lives they dream to live.
{11329}{11400}Now, the important thing about this story
{11401}{11479}is that we both ended up catching the winds of luck
{11479}{11534}as a result of his thank-you note.
{11535}{11623}But it was the winds that we didn't expect in the first place.
{11654}{11705}Over the course of the last couple of years,
{11705}{11781}I've come up with some tactics for my own life
{11781}{11838}to help me really foster appreciation.
{11853}{11941}My favorite is that at the end of every single day,
{11942}{12036}I look at my calendar and I review all the people I met with,
{12036}{12113}and I send thank-you notes to every single person.
{12113}{12168}It only takes a few minutes,
{12168}{12213}but at the end of every day,
{12213}{12295}I feel incredibly grateful and appreciative,
{12296}{12359}and I promise you it has increased my luck.
{12380}{12470}So first, you need to take some risks and get out of your comfort zone.
{12471}{12532}Second, you need to show appreciation.
{12533}{12630}And third, you want to change your relationship with ideas.
{12655}{12738}Most people look at new ideas that come there way and they judge them.
{12739}{12807}"That's a great idea" or "That's a terrible idea."
{12808}{12883}But it's actually much more nuanced.
{12901}{12947}Ideas are neither good or bad.
{12948}{13068}And in fact, the seeds of terrible ideas are often something truly remarkable.
{13101}{13181}One of my favorite exercises in my classes on creativity
{13182}{13283}is to help students foster an attitude of looking at terrible ideas
{13284}{13363}through the lens of possibilities.
{13379}{13432}So I give them a challenge:
{13433}{13514}to create an idea for a brand new restaurant.
{13527}{13600}They have to come up with the best ideas for a new restaurant
{13600}{13665}and the worst ideas for a new restaurant.
{13665}{13752}So the best ideas are things like a restaurant on a mountaintop
{13752}{13791}with a beautiful sunset,
{13791}{13864}or a restaurant on a boat with a gorgeous view.
{13864}{13984}And the terrible ideas are things like a restaurant in a garbage dump,
{13985}{14091}or a restaurant with terrible service that's really dirty,
{14091}{14177}or a restaurant that serves cockroach sushi.
{14211}{14264}So they hand all the ideas to me,
{14265}{14321}I read the great ideas out loud,
{14321}{14373}and then I rip them up and throw them away.
{14410}{14489}I then take the horrible ideas and redistribute them.
{14504}{14618}Each team now has an idea that another team thought was horrible,
{14619}{14689}and their challenge is to turn it into something brilliant.
{14725}{14754}Here's what happens.
{14773}{14895}Within about 10 seconds, someone says, "This is a fabulous idea."
{14896}{15012}And they have about three minutes before they pitch the idea to the class.
{15013}{15095}So the restaurant in the garbage dump? What does that turn into?
{15095}{15199}Well, they collect all the extra food from Michelin star restaurants
{15200}{15258}that was going to get thrown out,
{15258}{15323}and they have another restaurant at a much lower price,
{15323}{15352}with all the leftovers.
{15353}{15382}Pretty cool?
{15382}{15456}Or the restaurant that's dirty with terrible service?
{15467}{15560}Well, that turns into a restaurant that's a training ground
{15561}{15663}for future restauranteurs to figure out how to avoid all the pitfalls.
{15684}{15732}And the restaurant with cockroach sushi?
{15733}{15786}It turns into a sushi bar
{15787}{15864}with all sorts of really interesting and exotic ingredients.
{15898}{15975}If you look around at the companies,
{15976}{16052}the ventures that are really innovative around you,
{16053}{16143}the ones that we now take for granted that have changed our life,
{16144}{16176}well, you know what?
{16176}{16248}They all started out as crazy ideas.
{16249}{16317}They started ideas that when they pitched to other people,
{16318}{16396}most people said, "That's crazy, it will never work."
{16452}{16597}So, yes, sometimes people were born into terrible circumstances,
{16597}{16654}and sometimes, luck is a lightning bolt
{16655}{16729}that hits us with something wonderful or something terrible.
{16753}{16852}But the winds of luck are always there,
{16852}{16928}and if you're willing to take some risks,
{16929}{17017}if you're willing to really go out and show appreciation
{17017}{17128}and willing to really look at ideas, even if they're crazy,
{17128}{17173}through the lens of possibilities,
{17173}{17283}(SOUND EFFECT)
{17292}{17321}(SOUND EFFECT)
